package codegen

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDIGenerator_GeneratesWireFile(t *testing.T) {
	t.Parallel()

	dir := newWireFixture(t, wireComponentSource())

	if err := NewDIGenerator(dir).Generate(context.Background()); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	generated := readFile(t, filepath.Join(dir, "helix_wire_gen.go"))
	for _, want := range []string{
		"// Code generated by helix generate. DO NOT EDIT.",
		"package app",
		"helix.RegisterWireSetup(func(c *core.Container) error {",
		"userRepository := &UserRepository{}",
		"userService := &UserService{Repo: userRepository}",
		"if err := c.Register(userService); err != nil {",
	} {
		if !strings.Contains(generated, want) {
			t.Fatalf("generated file missing %q\n--- generated ---\n%s", want, generated)
		}
	}
}

func TestDIGenerator_GeneratedFileHasNoReflectImport(t *testing.T) {
	t.Parallel()

	dir := newWireFixture(t, wireComponentSource())

	if err := NewDIGenerator(dir).Generate(context.Background()); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	generated := readFile(t, filepath.Join(dir, "helix_wire_gen.go"))
	if strings.Contains(generated, `"reflect"`) {
		t.Fatalf("generated file imports reflect\n--- generated ---\n%s", generated)
	}
}

func TestDIGenerator_GeneratedFileHasCodegenHeader(t *testing.T) {
	t.Parallel()

	dir := newWireFixture(t, wireComponentSource())

	if err := NewDIGenerator(dir).Generate(context.Background()); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	generated := readFile(t, filepath.Join(dir, "helix_wire_gen.go"))
	if !strings.HasPrefix(generated, "// Code generated by helix generate. DO NOT EDIT.") {
		t.Fatalf("generated header = %q", strings.SplitN(generated, "\n", 2)[0])
	}
}

func TestDIGenerator_TopologicalOrder(t *testing.T) {
	t.Parallel()

	dir := newWireFixture(t, wireComponentSource())

	if err := NewDIGenerator(dir).Generate(context.Background()); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	generated := readFile(t, filepath.Join(dir, "helix_wire_gen.go"))
	repoIndex := strings.Index(generated, "userRepository := &UserRepository{}")
	serviceIndex := strings.Index(generated, "userService := &UserService{Repo: userRepository}")
	if repoIndex == -1 || serviceIndex == -1 {
		t.Fatalf("generated file missing expected instantiations\n--- generated ---\n%s", generated)
	}
	if repoIndex > serviceIndex {
		t.Fatalf("dependency instantiated after dependent\n--- generated ---\n%s", generated)
	}
}

func TestDIGenerator_CyclicDependencyError(t *testing.T) {
	t.Parallel()

	dir := newWireFixture(t, `package app

import "github.com/enokdev/helix"

type A struct {
	helix.Service
	B *B `+"`inject:\"true\"`"+`
}

type B struct {
	helix.Service
	A *A `+"`inject:\"true\"`"+`
}
`)

	err := NewDIGenerator(dir).Generate(context.Background())
	if err == nil || !strings.Contains(err.Error(), "cyclic dependency") {
		t.Fatalf("Generate() error = %v, want cyclic dependency", err)
	}
}

func TestDIGenerator_IdempotentTwoRuns(t *testing.T) {
	t.Parallel()

	dir := newWireFixture(t, wireComponentSource())
	generator := NewDIGenerator(dir)

	if err := generator.Generate(context.Background()); err != nil {
		t.Fatalf("first Generate() error = %v", err)
	}
	path := filepath.Join(dir, "helix_wire_gen.go")
	first := readFile(t, path)
	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat generated file: %v", err)
	}

	if err := generator.Generate(context.Background()); err != nil {
		t.Fatalf("second Generate() error = %v", err)
	}
	second := readFile(t, path)
	infoAfter, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat generated file after second run: %v", err)
	}
	if first != second {
		t.Fatal("generated content changed on second run")
	}
	if !info.ModTime().Equal(infoAfter.ModTime()) {
		t.Fatal("generated file was rewritten despite identical content")
	}
}

func TestDIGenerator_NoComponentsNoFile(t *testing.T) {
	t.Parallel()

	dir := newWireFixture(t, `package app

type Plain struct{}
`)

	if err := NewDIGenerator(dir).Generate(context.Background()); err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "helix_wire_gen.go")); !os.IsNotExist(err) {
		t.Fatalf("helix_wire_gen.go stat error = %v, want not exist", err)
	}
}

func newWireFixture(t *testing.T, source string) string {
	t.Helper()

	dir := t.TempDir()
	writeFixture(t, dir, "go.mod", "module example.test/wire\n\ngo 1.21.0\n")
	writeFixture(t, dir, "app.go", source)
	return dir
}

func wireComponentSource() string {
	return `package app

import "github.com/enokdev/helix"

type UserRepository struct {
	helix.Repository
}

type UserService struct {
	helix.Service
	Repo *UserRepository ` + "`inject:\"true\"`" + `
}
`
}
