package codegen

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestGeneratorCreatesRepositoryQueries(t *testing.T) {
	dir := t.TempDir()
	writeFixture(t, dir, "repository.go", validRepositorySource())

	result, err := NewGenerator(dir).Generate(context.Background())
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}
	if result.GeneratedFiles != 1 {
		t.Fatalf("GeneratedFiles = %d, want 1", result.GeneratedFiles)
	}

	generatedPath := filepath.Join(dir, "user_repository_query_gen.go")
	generated := readFile(t, generatedPath)
	for _, want := range []string{
		"// Code generated by helix generate. DO NOT EDIT.",
		"type userRepositoryGen struct",
		"func NewUserRepository(db *gormlib.DB) UserRepository",
		"func (r *userRepositoryGen) FindByEmail(ctx context.Context, email string) (*User, error)",
		`clause.Eq{Column: emailColumn, Value: email}`,
		`"%" + datagorm.EscapeLike(name) + "%"`,
		"clause.Gt{Column: ageColumn, Value: age}",
		"query = query.Where(clause.Eq{Column: emailColumn, Value: email})",
		"query = query.Where(clause.Eq{Column: ageColumn, Value: age})",
		"clause.OrderByColumn{Column: createdAtColumn, Desc: true}",
	} {
		if !strings.Contains(generated, want) {
			t.Fatalf("generated file missing %q\n--- generated ---\n%s", want, generated)
		}
	}
}

func TestGeneratorIsDeterministicAndDoesNotRewriteIdenticalFile(t *testing.T) {
	dir := t.TempDir()
	writeFixture(t, dir, "repository.go", validRepositorySource())

	if _, err := NewGenerator(dir).Generate(context.Background()); err != nil {
		t.Fatalf("first Generate returned error: %v", err)
	}
	generatedPath := filepath.Join(dir, "user_repository_query_gen.go")
	first := readFile(t, generatedPath)
	info, err := os.Stat(generatedPath)
	if err != nil {
		t.Fatalf("stat generated file: %v", err)
	}

	if _, err := NewGenerator(dir).Generate(context.Background()); err != nil {
		t.Fatalf("second Generate returned error: %v", err)
	}
	second := readFile(t, generatedPath)
	infoAfter, err := os.Stat(generatedPath)
	if err != nil {
		t.Fatalf("stat generated file after second run: %v", err)
	}

	if first != second {
		t.Fatal("generated content changed between identical runs")
	}
	if !info.ModTime().Equal(infoAfter.ModTime()) {
		t.Fatal("identical second generation rewrote the generated file")
	}
}

func TestGeneratorRejectsInvalidDirectives(t *testing.T) {
	tests := []struct {
		name    string
		comment string
	}{
		{name: "space after slashes", comment: "// helix:query auto"},
		{name: "plus directive", comment: "//+helix:query auto"},
		{name: "missing space", comment: "//helix:queryauto"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			writeFixture(t, dir, "repository.go", strings.Replace(validRepositorySource(), "//helix:query auto", tt.comment, 1))

			_, err := NewGenerator(dir).Generate(context.Background())
			if err == nil {
				t.Fatal("Generate returned nil error")
			}
			if !strings.Contains(err.Error(), "cli/codegen: parse query directive UserRepository.FindByEmail") {
				t.Fatalf("error = %v, want directive context", err)
			}
		})
	}
}

func TestGeneratorRejectsUnsupportedMethodsWithoutPartialFile(t *testing.T) {
	dir := t.TempDir()
	writeFixture(t, dir, "repository.go", strings.Replace(
		validRepositorySource(),
		"FindByAgeGreaterThan(ctx context.Context, age int) ([]User, error)",
		"FindByAgeLessThan(ctx context.Context, age int) ([]User, error)",
		1,
	))

	_, err := NewGenerator(dir).Generate(context.Background())
	if err == nil {
		t.Fatal("Generate returned nil error")
	}
	if !strings.Contains(err.Error(), "UserRepository.FindByAgeLessThan") {
		t.Fatalf("error = %v, want method context", err)
	}
	if _, statErr := os.Stat(filepath.Join(dir, "user_repository_query_gen.go")); !os.IsNotExist(statErr) {
		t.Fatalf("generated file exists after failed generation, stat err: %v", statErr)
	}
}

func TestGeneratedRepositoryCompiles(t *testing.T) {
	dir := t.TempDir()
	repoRoot := repoRoot(t)
	writeFixture(t, dir, "go.mod", "module example.test/generated\n\ngo 1.21.0\n\nrequire github.com/enokdev/helix v0.0.0\n\nreplace github.com/enokdev/helix => "+repoRoot+"\n")
	writeFixture(t, dir, "repository.go", validRepositorySource())

	if _, err := NewGenerator(dir).Generate(context.Background()); err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	tidy := exec.Command("go", "mod", "tidy")
	tidy.Dir = dir
	if output, err := tidy.CombinedOutput(); err != nil {
		t.Fatalf("go mod tidy failed: %v\n%s", err, output)
	}

	cmd := exec.Command("go", "test", ".")
	cmd.Dir = dir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("generated package did not compile: %v\n%s", err, output)
	}
}

func TestGeneratorCreatesTransactionalWrappers(t *testing.T) {
	dir := t.TempDir()
	writeFixture(t, dir, "service.go", validTransactionalServiceSource())

	result, err := NewGenerator(dir).Generate(context.Background())
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}
	if result.GeneratedFiles != 1 {
		t.Fatalf("GeneratedFiles = %d, want 1", result.GeneratedFiles)
	}

	generatedPath := filepath.Join(dir, "user_service_txn_gen.go")
	generated := readFile(t, generatedPath)
	for _, want := range []string{
		"// Code generated by helix generate. DO NOT EDIT.",
		"type userServiceTransactional struct",
		"func NewUserServiceTransactional(target *UserService, txManager data.TransactionManager[*gormlib.DB]) *userServiceTransactional",
		"func (w *userServiceTransactional) CreateUser(ctx context.Context, user *User) error",
		"return w.txManager.WithinTransaction(ctx, func(txCtx context.Context, _ data.Transaction[*gormlib.DB]) error {",
		"return w.target.CreateUser(txCtx, user)",
		"func (w *userServiceTransactional) BuildUser(ctx context.Context, name string) (*User, error)",
		"var result0 *User",
		"result0, callErr = w.target.BuildUser(txCtx, name)",
		"return result0, nil",
	} {
		if !strings.Contains(generated, want) {
			t.Fatalf("generated file missing %q\n--- generated ---\n%s", want, generated)
		}
	}
}

func TestGeneratorRejectsInvalidTransactionalDirectives(t *testing.T) {
	tests := []struct {
		name    string
		comment string
	}{
		{name: "space after slashes", comment: "// helix:transactional"},
		{name: "plus directive", comment: "//+helix:transactional"},
		{name: "extra option", comment: "//helix:transactional readOnly"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			writeFixture(t, dir, "service.go", strings.Replace(validTransactionalServiceSource(), "//helix:transactional", tt.comment, 1))

			_, err := NewGenerator(dir).Generate(context.Background())
			if err == nil {
				t.Fatal("Generate returned nil error")
			}
			if !strings.Contains(err.Error(), "parse transactional directive") || !strings.Contains(err.Error(), "UserService.CreateUser") {
				t.Fatalf("error = %v, want transactional directive context", err)
			}
		})
	}
}

func TestGeneratorRejectsInvalidTransactionalMethodWithoutPartialFile(t *testing.T) {
	tests := []struct {
		name        string
		replacement string
		want        string
	}{
		{
			name:        "missing context",
			replacement: "func (s *UserService) CreateUser(user *User) error",
			want:        "missing context.Context first parameter",
		},
		{
			name:        "receiver value",
			replacement: "func (s UserService) CreateUser(ctx context.Context, user *User) error",
			want:        "receiver must be pointer to struct",
		},
		{
			name:        "missing error",
			replacement: "func (s *UserService) CreateUser(ctx context.Context, user *User)",
			want:        "must return error as final result",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			source := strings.Replace(
				validTransactionalServiceSource(),
				"func (s *UserService) CreateUser(ctx context.Context, user *User) error",
				tt.replacement,
				1,
			)
			writeFixture(t, dir, "service.go", source)

			_, err := NewGenerator(dir).Generate(context.Background())
			if err == nil {
				t.Fatal("Generate returned nil error")
			}
			if !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("error = %v, want %q", err, tt.want)
			}
			if _, statErr := os.Stat(filepath.Join(dir, "user_service_txn_gen.go")); !os.IsNotExist(statErr) {
				t.Fatalf("generated file exists after failed generation, stat err: %v", statErr)
			}
		})
	}
}

func validRepositorySource() string {
	return `package generated

import (
	"context"
	"time"

	"github.com/enokdev/helix/data"
	gormlib "gorm.io/gorm"
)

type User struct {
	ID        int
	Email     string
	Name      string
	Age       int
	CreatedAt time.Time
}

type UserRepository interface {
	data.Repository[User, int, *gormlib.DB]

	//helix:query auto
	FindByEmail(ctx context.Context, email string) (*User, error)

	//helix:query auto
	FindByNameContaining(ctx context.Context, name string) ([]User, error)

	//helix:query auto
	FindByAgeGreaterThan(ctx context.Context, age int) ([]User, error)

	//helix:query auto
	FindByEmailAndAge(ctx context.Context, email string, age int) (*User, error)

	//helix:query auto
	FindAllOrderByCreatedAtDesc(ctx context.Context) ([]User, error)
}
`
}

func validTransactionalServiceSource() string {
	return `package generated

import (
	"context"
)

type User struct {
	ID   int
	Name string
}

type UserWriter interface {
	CreateUser(ctx context.Context, user *User) error
	BuildUser(ctx context.Context, name string) (*User, error)
}

type UserService struct{}

//helix:transactional
func (s *UserService) CreateUser(ctx context.Context, user *User) error {
	return nil
}

//helix:transactional
func (s *UserService) BuildUser(ctx context.Context, name string) (*User, error) {
	return &User{Name: name}, nil
}
`
}

func writeFixture(t *testing.T, dir, name, content string) {
	t.Helper()

	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(content)
}

func repoRoot(t *testing.T) string {
	t.Helper()

	wd, err := os.Getwd()
	if err != nil {
		t.Fatalf("get wd: %v", err)
	}
	return filepath.Clean(filepath.Join(wd, "..", "..", ".."))
}
