package codegen

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestImportsGenerator_WritesImportsFile(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	// go.mod
	writeFixture(t, root, "go.mod", "module example.test/myapp\n\ngo 1.21.0\n")
	// Simulated generated register.go in orders/
	ordersDir := filepath.Join(root, "orders")
	if err := os.MkdirAll(ordersDir, 0o755); err != nil {
		t.Fatalf("mkdir orders: %v", err)
	}
	writeFixture(t, ordersDir, "register.go",
		"// Code generated by helix; DO NOT EDIT.\npackage orders\n\nimport \"github.com/enokdev/helix\"\n\nfunc init() {\n\thelix.RegisterComponents()\n}\n")
	// cmd/ with main.go
	cmdDir := filepath.Join(root, "cmd")
	if err := os.MkdirAll(cmdDir, 0o755); err != nil {
		t.Fatalf("mkdir cmd: %v", err)
	}
	writeFixture(t, cmdDir, "main.go", "package main\n\nfunc main() {}\n")

	gen := NewImportsGenerator(root)
	result, err := gen.Generate()
	if err != nil {
		t.Fatalf("ImportsGenerator.Generate() error = %v", err)
	}

	if len(result.Files) == 0 {
		t.Fatal("ImportsGenerator.Generate() produced no files")
	}

	outPath := filepath.Join(root, "cmd", "helix_imports_gen.go")
	if _, err := os.Stat(outPath); err != nil {
		t.Fatalf("helix_imports_gen.go not created: %v", err)
	}

	content := readFile(t, outPath)
	if !strings.Contains(content, "// Code generated by helix; DO NOT EDIT.") {
		t.Fatalf("missing codegen header:\n%s", content)
	}
	if !strings.Contains(content, `_ "example.test/myapp/orders"`) {
		t.Fatalf("missing blank import for orders:\n%s", content)
	}
	if !strings.Contains(content, "package main") {
		t.Fatalf("wrong package name:\n%s", content)
	}
}

func TestImportsGenerator_NoModules_NoFileWritten(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(t, root, "go.mod", "module example.test/empty\n\ngo 1.21.0\n")

	gen := NewImportsGenerator(root)
	result, err := gen.Generate()
	if err != nil {
		t.Fatalf("ImportsGenerator.Generate() error = %v", err)
	}

	if len(result.Files) != 0 {
		t.Fatalf("ImportsGenerator.Generate() wrote files unexpectedly: %v", result.Files)
	}
	if _, err := os.Stat(filepath.Join(root, "cmd", "helix_imports_gen.go")); !os.IsNotExist(err) {
		t.Fatal("helix_imports_gen.go should not be created when no modules exist")
	}
	if _, err := os.Stat(filepath.Join(root, "helix_imports_gen.go")); !os.IsNotExist(err) {
		t.Fatal("root-level helix_imports_gen.go should not be created when no modules exist")
	}
}

func TestImportsGenerator_StaleFileRemovedWhenModulesDisappear(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(t, root, "go.mod", "module example.com/testapp\n\ngo 1.21\n")
	writeFixture(t, root, "main.go", "package main\n\nfunc main() {}\n")
	pkgDir := filepath.Join(root, "pkg")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatalf("mkdir pkg: %v", err)
	}
	registerPath := filepath.Join(pkgDir, "register.go")
	writeFixture(t, pkgDir, "register.go", "// Code generated by helix; DO NOT EDIT.\npackage pkg\n")

	gen := NewImportsGenerator(root)
	if _, err := gen.Generate(); err != nil {
		t.Fatalf("first Generate() error = %v", err)
	}

	outPath := filepath.Join(root, "helix_imports_gen.go")
	if _, err := os.Stat(outPath); err != nil {
		t.Fatalf("helix_imports_gen.go not created: %v", err)
	}

	if err := os.Remove(registerPath); err != nil {
		t.Fatalf("remove register.go: %v", err)
	}

	if _, err := gen.Generate(); err != nil {
		t.Fatalf("second Generate() error = %v", err)
	}

	if _, err := os.Stat(outPath); !os.IsNotExist(err) {
		t.Fatalf("helix_imports_gen.go should be removed when modules disappear, err=%v", err)
	}
}

func TestImportsGenerator_StaleFileRemovedFromOldLocation(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(t, root, "go.mod", "module example.com/testapp\n\ngo 1.21\n")
	cmdDir := filepath.Join(root, "cmd")
	if err := os.MkdirAll(cmdDir, 0o755); err != nil {
		t.Fatalf("mkdir cmd: %v", err)
	}
	writeFixture(t, cmdDir, "main.go", "package main\n\nfunc main() {}\n")
	pkgDir := filepath.Join(root, "pkg")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatalf("mkdir pkg: %v", err)
	}
	registerPath := filepath.Join(pkgDir, "register.go")
	writeFixture(t, pkgDir, "register.go", "// Code generated by helix; DO NOT EDIT.\npackage pkg\n")

	gen := NewImportsGenerator(root)
	if _, err := gen.Generate(); err != nil {
		t.Fatalf("first Generate() error = %v", err)
	}

	cmdOutPath := filepath.Join(root, "cmd", "helix_imports_gen.go")
	if _, err := os.Stat(cmdOutPath); err != nil {
		t.Fatalf("cmd/helix_imports_gen.go not created: %v", err)
	}

	if err := os.Remove(registerPath); err != nil {
		t.Fatalf("remove register.go: %v", err)
	}
	if err := os.Remove(filepath.Join(cmdDir, "main.go")); err != nil {
		t.Fatalf("remove cmd/main.go: %v", err)
	}

	if _, err := gen.Generate(); err != nil {
		t.Fatalf("second Generate() error = %v", err)
	}

	for _, path := range []string{cmdOutPath, filepath.Join(root, "helix_imports_gen.go")} {
		if _, err := os.Stat(path); !os.IsNotExist(err) {
			t.Fatalf("stale imports file should be removed at %s, err=%v", path, err)
		}
	}
}

func TestImportsGenerator_SkipsGenerationWhenNoMainPackage(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(t, root, "go.mod", "module example.com/testapp\n\ngo 1.21\n")
	cmdAppDir := filepath.Join(root, "cmd", "myapp")
	if err := os.MkdirAll(cmdAppDir, 0o755); err != nil {
		t.Fatalf("mkdir cmd/myapp: %v", err)
	}
	writeFixture(t, cmdAppDir, "main.go", "package main\n\nfunc main() {}\n")
	pkgDir := filepath.Join(root, "pkg")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatalf("mkdir pkg: %v", err)
	}
	writeFixture(t, pkgDir, "register.go", "// Code generated by helix; DO NOT EDIT.\npackage pkg\n")

	gen := NewImportsGenerator(root)
	result, err := gen.Generate()
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	if len(result.Files) != 0 {
		t.Fatalf("Generate() wrote files unexpectedly: %v", result.Files)
	}

	for _, path := range []string{
		filepath.Join(root, "helix_imports_gen.go"),
		filepath.Join(root, "cmd", "helix_imports_gen.go"),
	} {
		if _, err := os.Stat(path); !os.IsNotExist(err) {
			t.Fatalf("imports file should not exist at %s, err=%v", path, err)
		}
	}
}

func TestImportsGenerator_StaleRemovedWhenMainPackageDisappears(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(t, root, "go.mod", "module example.com/testapp\n\ngo 1.21\n")
	cmdDir := filepath.Join(root, "cmd")
	if err := os.MkdirAll(cmdDir, 0o755); err != nil {
		t.Fatalf("mkdir cmd: %v", err)
	}
	mainPath := filepath.Join(cmdDir, "main.go")
	writeFixture(t, cmdDir, "main.go", "package main\n\nfunc main() {}\n")
	pkgDir := filepath.Join(root, "pkg")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatalf("mkdir pkg: %v", err)
	}
	writeFixture(t, pkgDir, "register.go", "// Code generated by helix; DO NOT EDIT.\npackage pkg\n")

	gen := NewImportsGenerator(root)
	if _, err := gen.Generate(); err != nil {
		t.Fatalf("first Generate() error = %v", err)
	}

	cmdOutPath := filepath.Join(root, "cmd", "helix_imports_gen.go")
	if _, err := os.Stat(cmdOutPath); err != nil {
		t.Fatalf("cmd/helix_imports_gen.go not created: %v", err)
	}

	if err := os.Remove(mainPath); err != nil {
		t.Fatalf("remove cmd/main.go: %v", err)
	}

	result, err := gen.Generate()
	if err != nil {
		t.Fatalf("second Generate() error = %v", err)
	}
	if len(result.Files) != 0 {
		t.Fatalf("second Generate() wrote files unexpectedly: %v", result.Files)
	}

	for _, path := range []string{
		cmdOutPath,
		filepath.Join(root, "helix_imports_gen.go"),
	} {
		if _, err := os.Stat(path); !os.IsNotExist(err) {
			t.Fatalf("imports file should not exist at %s, err=%v", path, err)
		}
	}
}

func TestImportsGenerator_StaleRemovedWhenOutputDirChanges(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(t, root, "go.mod", "module example.com/testapp\n\ngo 1.21\n")
	cmdDir := filepath.Join(root, "cmd")
	if err := os.MkdirAll(cmdDir, 0o755); err != nil {
		t.Fatalf("mkdir cmd: %v", err)
	}
	writeFixture(t, cmdDir, "main.go", "package main\n\nfunc main() {}\n")
	pkgDir := filepath.Join(root, "pkg")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatalf("mkdir pkg: %v", err)
	}
	writeFixture(t, pkgDir, "register.go", "// Code generated by helix; DO NOT EDIT.\npackage pkg\n")

	gen := NewImportsGenerator(root)
	if _, err := gen.Generate(); err != nil {
		t.Fatalf("first Generate() error = %v", err)
	}

	cmdOutPath := filepath.Join(root, "cmd", "helix_imports_gen.go")
	if _, err := os.Stat(cmdOutPath); err != nil {
		t.Fatalf("cmd/helix_imports_gen.go not created: %v", err)
	}

	if err := os.Remove(filepath.Join(cmdDir, "main.go")); err != nil {
		t.Fatalf("remove cmd/main.go: %v", err)
	}
	writeFixture(t, root, "main.go", "package main\n\nfunc main() {}\n")

	if _, err := gen.Generate(); err != nil {
		t.Fatalf("second Generate() error = %v", err)
	}

	rootOutPath := filepath.Join(root, "helix_imports_gen.go")
	if _, err := os.Stat(rootOutPath); err != nil {
		t.Fatalf("root helix_imports_gen.go not created: %v", err)
	}
	if _, err := os.Stat(cmdOutPath); !os.IsNotExist(err) {
		t.Fatalf("cmd/helix_imports_gen.go should be removed, err=%v", err)
	}
}

func TestImportsGenerator_MultipleModules_SortedImports(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(t, root, "go.mod", "module example.test/multi\n\ngo 1.21.0\n")
	writeFixture(t, root, "main.go", "package main\n\nfunc main() {}\n")

	for _, pkg := range []string{"zebras", "apples", "mangoes"} {
		dir := filepath.Join(root, pkg)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			t.Fatalf("mkdir %s: %v", pkg, err)
		}
		writeFixture(t, dir, "register.go",
			"// Code generated by helix; DO NOT EDIT.\npackage "+pkg+"\n\nimport \"github.com/enokdev/helix\"\n\nfunc init() {}\n")
	}

	gen := NewImportsGenerator(root)
	_, err := gen.Generate()
	if err != nil {
		t.Fatalf("ImportsGenerator.Generate() error = %v", err)
	}

	// No cmd/ dir, so output is at root
	outPath := filepath.Join(root, "helix_imports_gen.go")
	content := readFile(t, outPath)

	applePos := strings.Index(content, "apples")
	mangoPos := strings.Index(content, "mangoes")
	zebraPos := strings.Index(content, "zebras")
	if applePos >= mangoPos || mangoPos >= zebraPos {
		t.Fatalf("imports not sorted alphabetically:\n%s", content)
	}
}

func TestImportsGenerator_FallsBackToRoot_WhenNoCmdDir(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(t, root, "go.mod", "module example.test/nomd\n\ngo 1.21.0\n")
	// No cmd/ directory
	pkgDir := filepath.Join(root, "orders")
	if err := os.MkdirAll(pkgDir, 0o755); err != nil {
		t.Fatalf("mkdir orders: %v", err)
	}
	writeFixture(t, pkgDir, "register.go",
		"// Code generated by helix; DO NOT EDIT.\npackage orders\n\nimport \"github.com/enokdev/helix\"\n\nfunc init() {}\n")
	// main.go at root (no cmd/)
	writeFixture(t, root, "main.go", "package main\n\nfunc main() {}\n")

	gen := NewImportsGenerator(root)
	_, err := gen.Generate()
	if err != nil {
		t.Fatalf("ImportsGenerator.Generate() error = %v", err)
	}

	outPath := filepath.Join(root, "helix_imports_gen.go")
	if _, err := os.Stat(outPath); err != nil {
		t.Fatalf("helix_imports_gen.go not created at root: %v", err)
	}
}

func TestImportsGenerator_IdempotentTwoRuns(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(t, root, "go.mod", "module example.test/idem\n\ngo 1.21.0\n")
	writeFixture(t, root, "main.go", "package main\n\nfunc main() {}\n")
	ordersDir := filepath.Join(root, "orders")
	if err := os.MkdirAll(ordersDir, 0o755); err != nil {
		t.Fatalf("mkdir orders: %v", err)
	}
	writeFixture(t, ordersDir, "register.go",
		"// Code generated by helix; DO NOT EDIT.\npackage orders\n\nimport \"github.com/enokdev/helix\"\n\nfunc init() {}\n")

	gen := NewImportsGenerator(root)
	if _, err := gen.Generate(); err != nil {
		t.Fatalf("first Generate() error = %v", err)
	}
	if _, err := gen.Generate(); err != nil {
		t.Fatalf("second Generate() error = %v", err)
	}

	outPath := filepath.Join(root, "helix_imports_gen.go")
	content := readFile(t, outPath)
	count := strings.Count(content, `"example.test/idem/orders"`)
	if count != 1 {
		t.Fatalf("import appears %d times, want 1:\n%s", count, content)
	}
}
