package codegen

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/enokdev/helix/cli/internal/gofmtx"
)

const (
	importsGenHeader   = "// Code generated by helix; DO NOT EDIT."
	importsGenFilename = "helix_imports_gen.go"
)

// ImportsGeneratorResult describes the output of one ImportsGenerator run.
type ImportsGeneratorResult struct {
	Files []string
}

// ImportsGenerator scans a project for generated register.go files and writes
// a helix_imports_gen.go file with blank imports that trigger their init().
type ImportsGenerator struct {
	dir string
}

// NewImportsGenerator creates a generator rooted at dir.
func NewImportsGenerator(dir string) *ImportsGenerator {
	if dir == "" {
		dir = "."
	}
	return &ImportsGenerator{dir: dir}
}

// Generate scans for register.go files and writes helix_imports_gen.go.
// Returns an empty result when no generated register.go files are found.
func (g *ImportsGenerator) Generate() (ImportsGeneratorResult, error) {
	root, err := filepath.Abs(g.dir)
	if err != nil {
		return ImportsGeneratorResult{}, fmt.Errorf("cli/codegen: imports gen: resolve root: %w", err)
	}

	moduleRoot, modulePath, err := findGoModule(root)
	if err != nil {
		return ImportsGeneratorResult{}, err
	}

	importPaths, err := findRegisteredModuleImports(moduleRoot, modulePath)
	if err != nil {
		return ImportsGeneratorResult{}, err
	}
	if len(importPaths) == 0 {
		// Remove any stale file from either candidate location.
		candidates := []string{
			filepath.Join(root, importsGenFilename),
			filepath.Join(root, "cmd", importsGenFilename),
		}
		for _, candidate := range candidates {
			if err := os.Remove(candidate); err != nil && !os.IsNotExist(err) {
				return ImportsGeneratorResult{}, fmt.Errorf("imports gen: remove stale %s: %w", candidate, err)
			}
		}
		return ImportsGeneratorResult{}, nil
	}

	outDir, ok := resolveOutputDir(root)
	if !ok {
		// No main package found — clean up stale files from both candidate locations.
		for _, candidate := range []string{
			filepath.Join(root, importsGenFilename),
			filepath.Join(root, "cmd", importsGenFilename),
		} {
			if err := os.Remove(candidate); err != nil && !os.IsNotExist(err) {
				return ImportsGeneratorResult{}, fmt.Errorf("imports gen: remove stale %s: %w", candidate, err)
			}
		}
		return ImportsGeneratorResult{}, nil
	}
	outPath := filepath.Join(outDir, importsGenFilename)

	content, err := renderImportsFile(importPaths)
	if err != nil {
		return ImportsGeneratorResult{}, err
	}

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return ImportsGeneratorResult{}, fmt.Errorf("cli/codegen: imports gen: mkdir %s: %w", outDir, err)
	}

	// Remove stale file from the other candidate location (handles output-dir change).
	allCandidates := []string{
		filepath.Join(root, importsGenFilename),
		filepath.Join(root, "cmd", importsGenFilename),
	}
	for _, candidate := range allCandidates {
		if candidate == outPath {
			continue
		}
		if err := os.Remove(candidate); err != nil && !os.IsNotExist(err) {
			return ImportsGeneratorResult{}, fmt.Errorf("imports gen: remove stale %s: %w", candidate, err)
		}
	}

	changed, err := writeFileIfChanged(outPath, content)
	if err != nil {
		return ImportsGeneratorResult{}, fmt.Errorf("cli/codegen: imports gen: write %s: %w", outPath, err)
	}
	if !changed {
		return ImportsGeneratorResult{Files: []string{outPath}}, nil
	}

	return ImportsGeneratorResult{Files: []string{outPath}}, nil
}

// findRegisteredModuleImports walks the project tree and returns sorted import
// paths for every package that contains a generated register.go file.
func findRegisteredModuleImports(root, modulePath string) ([]string, error) {
	importsSet := make(map[string]struct{})

	err := filepath.WalkDir(root, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			if path != root && shouldSkipDir(d.Name()) {
				return filepath.SkipDir
			}
			return nil
		}
		if d.Name() != "register.go" {
			return nil
		}

		content, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("cli/codegen: imports gen: read %s: %w", path, err)
		}
		if !strings.HasPrefix(strings.TrimSpace(string(content)), importsGenHeader) {
			return nil
		}

		dir := filepath.Dir(path)
		importPath, err := importPathForDir(root, modulePath, dir)
		if err != nil {
			return fmt.Errorf("imports gen: import path for %s: %w", dir, err)
		}
		importsSet[importPath] = struct{}{}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("cli/codegen: imports gen: walk %s: %w", root, err)
	}

	imports := make([]string, 0, len(importsSet))
	for importPath := range importsSet {
		imports = append(imports, importPath)
	}
	sort.Strings(imports)
	return imports, nil
}

// resolveOutputDir returns the directory where helix_imports_gen.go should be
// written and whether a valid main package was found.
// Priority: cmd/ (if cmd/main.go exists) > root (if main.go exists) > skip.
func resolveOutputDir(root string) (string, bool) {
	if _, err := os.Stat(filepath.Join(root, "cmd", "main.go")); err == nil {
		return filepath.Join(root, "cmd"), true
	}
	if _, err := os.Stat(filepath.Join(root, "main.go")); err == nil {
		return root, true
	}
	return "", false
}

// renderImportsFile produces the formatted Go source for helix_imports_gen.go.
func renderImportsFile(importPaths []string) ([]byte, error) {
	sort.Strings(importPaths)
	var buf bytes.Buffer
	buf.WriteString(importsGenHeader + "\n\npackage main\n\nimport (\n")
	for _, imp := range importPaths {
		fmt.Fprintf(&buf, "\t_ %q\n", imp)
	}
	buf.WriteString(")\n")

	formatted, err := gofmtx.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("cli/codegen: imports gen: format: %w", err)
	}
	return formatted, nil
}
