package codegen

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestWebGenerator_GenerateRoutesFile(t *testing.T) {
	tempDir := t.TempDir()
	gen := NewWebGenerator(tempDir)

	routesByFile := map[string][]routeInfo{
		"user_controller.go": {
			{
				Controller:  "UserController",
				HandlerName: "List",
				Method:      "GET",
				Path:        "/users",
			},
			{
				Controller:  "UserController",
				HandlerName: "Show",
				Method:      "GET",
				Path:        "/users/:id",
			},
		},
	}

	outputPath := filepath.Join(tempDir, "helix_web_gen.go")
	err := gen.generateRoutesFile(outputPath, routesByFile)
	assert.NoError(t, err)

	// Verify file was created
	data, err := os.ReadFile(outputPath)
	assert.NoError(t, err)
	content := string(data)

	// Verify generated code structure
	assert.Contains(t, content, "package main")
	assert.Contains(t, content, "func initGeneratedRoutes()")
	assert.Contains(t, content, "internal.GlobalRouteRegistry()")
	assert.Contains(t, content, "\"GET\"")
	assert.Contains(t, content, "\"/users\"")
	assert.Contains(t, content, "UserController")
}

func TestWebGenerator_GenerateErrorHandlersFile(t *testing.T) {
	tempDir := t.TempDir()
	gen := NewWebGenerator(tempDir)

	handlersByFile := map[string][]handlerInfo{
		"error_handler.go": {
			{
				Controller: "AppErrorHandler",
				MethodName: "HandleValidationError",
				ErrorType:  "ValidationError",
			},
			{
				Controller: "AppErrorHandler",
				MethodName: "HandleNotFound",
				ErrorType:  "NotFoundError",
			},
		},
	}

	outputPath := filepath.Join(tempDir, "helix_error_handlers_gen.go")
	err := gen.generateHandlersFile(outputPath, handlersByFile)
	assert.NoError(t, err)

	// Verify file was created
	data, err := os.ReadFile(outputPath)
	assert.NoError(t, err)
	content := string(data)

	// Verify generated code structure
	assert.Contains(t, content, "package main")
	assert.Contains(t, content, "func initGeneratedErrorHandlers()")
	assert.Contains(t, content, "internal.GlobalErrorHandlerRegistry()")
	assert.Contains(t, content, "\"ValidationError\"")
	assert.Contains(t, content, "\"NotFoundError\"")
}

func TestWebGenerator_GenerateWithNoDirectives(t *testing.T) {
	tempDir := t.TempDir()
	// Change to temp dir to avoid scanning actual project
	oldWd, err := os.Getwd()
	if err != nil {
		t.Fatalf("os.Getwd() error = %v", err)
	}
	if err := os.Chdir(tempDir); err != nil {
		t.Fatalf("os.Chdir(tempDir) error = %v", err)
	}
	t.Cleanup(func() { _ = os.Chdir(oldWd) })

	gen := NewWebGenerator(tempDir)

	result, err := gen.Generate(context.Background())
	assert.NoError(t, err)
	assert.Equal(t, 0, len(result.Files))
}

func TestWebGenerator_ConvertScannerRoutes(t *testing.T) {
	scannerRoutes := []RouteDirective{
		{
			Method:     "GET",
			Path:       "/users",
			MethodName: "ListUsers",
			LineNum:    10,
		},
		{
			Method:     "POST",
			Path:       "/users",
			MethodName: "CreateUser",
			LineNum:    15,
		},
	}

	routes := convertScannerRoutes(scannerRoutes)
	assert.Equal(t, 2, len(routes))
	assert.Equal(t, "ListUsers", routes[0].HandlerName)
	assert.Equal(t, "GET", routes[0].Method)
	assert.Equal(t, "/users", routes[0].Path)
}

func TestWebGenerator_ConvertScannerHandlers(t *testing.T) {
	scannerHandlers := []ErrorHandlerDirective{
		{
			ErrorTypes: []string{"ValidationError", "BadRequestError"},
			MethodName: "HandleBadRequest",
			LineNum:    20,
		},
		{
			ErrorTypes: []string{"NotFoundError"},
			MethodName: "HandleNotFound",
			LineNum:    25,
		},
	}

	handlers := convertScannerHandlers(scannerHandlers)
	assert.Equal(t, 3, len(handlers)) // 2 from first + 1 from second
	assert.Equal(t, "ValidationError", handlers[0].ErrorType)
	assert.Equal(t, "BadRequestError", handlers[1].ErrorType)
	assert.Equal(t, "NotFoundError", handlers[2].ErrorType)
}

func TestWebGenerator_GeneratedRouteFileIsValid(t *testing.T) {
	tempDir := t.TempDir()
	gen := NewWebGenerator(tempDir)

	routesByFile := map[string][]routeInfo{
		"controller.go": {
			{
				Controller:  "UsersController",
				HandlerName: "Get",
				Method:      "GET",
				Path:        "/users/:id",
			},
		},
	}

	outputPath := filepath.Join(tempDir, "helix_web_gen.go")
	err := gen.generateRoutesFile(outputPath, routesByFile)
	assert.NoError(t, err)

	// Verify the generated Go code can be parsed
	data, err := os.ReadFile(outputPath)
	assert.NoError(t, err)

	content := string(data)
	// Check for code generation header
	assert.True(t, strings.HasPrefix(content, "// Code generated by helix generate"))
	// Check it's valid Go
	assert.Contains(t, content, "package main")
	assert.NotContains(t, content, "invalid")
}

func TestWebGenerator_GeneratedHandlerFileIsValid(t *testing.T) {
	tempDir := t.TempDir()
	gen := NewWebGenerator(tempDir)

	handlersByFile := map[string][]handlerInfo{
		"error_handler.go": {
			{
				Controller: "ErrorHandler",
				MethodName: "HandleError",
				ErrorType:  "CustomError",
			},
		},
	}

	outputPath := filepath.Join(tempDir, "helix_error_handlers_gen.go")
	err := gen.generateHandlersFile(outputPath, handlersByFile)
	assert.NoError(t, err)

	// Verify the generated Go code can be parsed
	data, err := os.ReadFile(outputPath)
	assert.NoError(t, err)

	content := string(data)
	// Check for code generation header
	assert.True(t, strings.HasPrefix(content, "// Code generated by helix generate"))
	// Check it's valid Go
	assert.Contains(t, content, "package main")
	assert.NotContains(t, content, "invalid")
}
