package codegen

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// GenerateResult contains information about the generation process.
type GenerateResult struct {
	Files []string
}

// WebGenerator generates Go code for the web layer.
type WebGenerator struct {
	dir     string
	scanner *WebScanner
}

// NewWebGenerator creates a new WebGenerator.
func NewWebGenerator(dir string) *WebGenerator {
	return &WebGenerator{
		dir:     dir,
		scanner: NewWebScanner(),
	}
}

// Generate scans for web directives and generates registration code.
func (g *WebGenerator) Generate(ctx context.Context) (GenerateResult, error) {
	if ctx == nil {
		return GenerateResult{}, fmt.Errorf("cli/codegen: web generate: nil context")
	}

	root := g.dir
	if root == "" {
		root = "."
	}

	// Find all .go files recursively
	var files []string
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}

		if info.IsDir() {
			// Skip vendor, test data, generated files
			if info.Name() == "vendor" || info.Name() == "testdata" || strings.HasPrefix(info.Name(), "_") {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") || strings.HasSuffix(path, "_gen.go") {
			return nil
		}
		files = append(files, path)
		return nil
	})
	if err != nil {
		return GenerateResult{}, err
	}

	routesByFile := make(map[string][]routeInfo)
	handlersByFile := make(map[string][]handlerInfo)

	for _, file := range files {
		select {
		case <-ctx.Done():
			return GenerateResult{}, ctx.Err()
		default:
		}

		routes, err := g.scanner.ScanControllerDirectives(file)
		if err != nil {
			return GenerateResult{}, err
		}
		if len(routes) > 0 {
			routesByFile[file] = convertScannerRoutes(routes)
		}

		handlers, err := g.scanner.ScanErrorHandlerDirectives(file)
		if err != nil {
			return GenerateResult{}, err
		}
		if len(handlers) > 0 {
			handlersByFile[file] = convertScannerHandlers(handlers)
		}
	}

	var generatedFiles []string

	if len(routesByFile) > 0 {
		outputPath := filepath.Join(root, "helix_web_gen.go")
		if err := g.generateRoutesFile(outputPath, routesByFile); err != nil {
			return GenerateResult{}, err
		}
		generatedFiles = append(generatedFiles, outputPath)
	}

	if len(handlersByFile) > 0 {
		outputPath := filepath.Join(root, "helix_error_handlers_gen.go")
		if err := g.generateHandlersFile(outputPath, handlersByFile); err != nil {
			return GenerateResult{}, err
		}
		generatedFiles = append(generatedFiles, outputPath)
	}

	return GenerateResult{Files: generatedFiles}, nil
}

type routeInfo struct {
	Controller   string
	HandlerName  string
	Method       string
	Path         string
	Guards       []string
	Interceptors []string
}

type handlerInfo struct {
	Controller string
	MethodName string
	ErrorType  string
}

func convertScannerRoutes(scannerRoutes []RouteDirective) []routeInfo {
	var routes []routeInfo
	for _, sr := range scannerRoutes {
		routes = append(routes, routeInfo{
			Controller:   sr.ControllerName,
			HandlerName:  sr.MethodName,
			Method:       sr.Method,
			Path:         sr.Path,
			Guards:       sr.Guards,
			Interceptors: sr.Interceptors,
		})
	}
	return routes
}

func convertScannerHandlers(scannerHandlers []ErrorHandlerDirective) []handlerInfo {
	var handlers []handlerInfo
	for _, sh := range scannerHandlers {
		for _, errorType := range sh.ErrorTypes {
			handlers = append(handlers, handlerInfo{
				Controller: sh.ControllerName,
				MethodName: sh.MethodName,
				ErrorType:  errorType,
			})
		}
	}
	return handlers
}

func (g *WebGenerator) generateRoutesFile(outputPath string, routesByFile map[string][]routeInfo) error {
	var allRoutes []routeInfo
	for _, routes := range routesByFile {
		allRoutes = append(allRoutes, routes...)
	}

	sort.Slice(allRoutes, func(i, j int) bool {
		if allRoutes[i].Controller != allRoutes[j].Controller {
			return allRoutes[i].Controller < allRoutes[j].Controller
		}
		if allRoutes[i].Path != allRoutes[j].Path {
			return allRoutes[i].Path < allRoutes[j].Path
		}
		return allRoutes[i].Method < allRoutes[j].Method
	})

	var buf bytes.Buffer
	buf.WriteString(`// Code generated by helix generate. DO NOT EDIT.
package main

import (
	"github.com/enokdev/helix"
	"github.com/enokdev/helix/web/internal"
)

func init() {
	helix.RegisterWebSetup(func() error {
		if err := initGeneratedRoutes(); err != nil {
			return err
		}
		return nil
	})
}

func initGeneratedRoutes() error {
	registry := internal.GlobalRouteRegistry()
`)

	routesByController := make(map[string][]routeInfo)
	for _, r := range allRoutes {
		routesByController[r.Controller] = append(routesByController[r.Controller], r)
	}

	var controllers []string
	for c := range routesByController {
		controllers = append(controllers, c)
	}
	sort.Strings(controllers)

	for _, controller := range controllers {
		routes := routesByController[controller]
		buf.WriteString(fmt.Sprintf("\n\tif err := registry.RegisterGeneratedRoutes(\"%s\",\n", controller))
		for i, route := range routes {
			if i > 0 {
				buf.WriteString(",\n")
			}

			guards := "nil"
			if len(route.Guards) > 0 {
				guards = fmt.Sprintf("[]string{%s}", formatStringSlice(route.Guards))
			}

			interceptors := "nil"
			if len(route.Interceptors) > 0 {
				interceptors = fmt.Sprintf("[]string{%s}", formatStringSlice(route.Interceptors))
			}

			buf.WriteString(fmt.Sprintf("\t\tinternal.RouteInfo{\n"+
				"\t\t\tMethod:       %#v,\n"+
				"\t\t\tPath:         %#v,\n"+
				"\t\t\tController:   %#v,\n"+
				"\t\t\tHandlerName:  %#v,\n"+
				"\t\t\tHandler:      (*%s).%s,\n"+
				"\t\t\tGuards:       %s,\n"+
				"\t\t\tInterceptors: %s,\n"+
				"\t\t}",
				route.Method, route.Path, route.Controller, route.HandlerName, route.Controller, route.HandlerName, guards, interceptors))
		}
		buf.WriteString(",\n\t); err != nil {\n\t\treturn err\n\t}\n")
	}

	buf.WriteString("\n\treturn nil\n}\n")

	return os.WriteFile(outputPath, buf.Bytes(), 0o644)
}

func (g *WebGenerator) generateHandlersFile(outputPath string, handlersByFile map[string][]handlerInfo) error {
	var allHandlers []handlerInfo
	for _, handlers := range handlersByFile {
		allHandlers = append(allHandlers, handlers...)
	}

	sort.Slice(allHandlers, func(i, j int) bool {
		if allHandlers[i].Controller != allHandlers[j].Controller {
			return allHandlers[i].Controller < allHandlers[j].Controller
		}
		if allHandlers[i].MethodName != allHandlers[j].MethodName {
			return allHandlers[i].MethodName < allHandlers[j].MethodName
		}
		return allHandlers[i].ErrorType < allHandlers[j].ErrorType
	})

	var buf bytes.Buffer
	buf.WriteString(`// Code generated by helix generate. DO NOT EDIT.
package main

import (
	"github.com/enokdev/helix"
	"github.com/enokdev/helix/web/internal"
)

func init() {
	helix.RegisterWebSetup(func() error {
		return initGeneratedErrorHandlers()
	})
}

func initGeneratedErrorHandlers() error {
	registry := internal.GlobalErrorHandlerRegistry()

	if err := registry.RegisterGeneratedErrorHandlers(
`)

	for i, handler := range allHandlers {
		if i > 0 {
			buf.WriteString(",\n")
		}
		buf.WriteString(fmt.Sprintf("\t\tinternal.ErrorHandlerInfo{\n"+
			"\t\t\tErrorType:  %#v,\n"+
			"\t\t\tController: %#v,\n"+
			"\t\t\tMethodName: %#v,\n"+
			"\t\t\tHandler:    (*%s).%s,\n"+
			"\t\t}",
			handler.ErrorType, handler.Controller, handler.MethodName, handler.Controller, handler.MethodName))
	}

	buf.WriteString(",\n\t); err != nil {\n\t\treturn err\n\t}\n\n\treturn nil\n}\n")

	return os.WriteFile(outputPath, buf.Bytes(), 0o644)
}

func formatStringSlice(slice []string) string {
	if len(slice) == 0 {
		return ""
	}
	var quoted []string
	for _, s := range slice {
		quoted = append(quoted, fmt.Sprintf("%#v", s))
	}
	return strings.Join(quoted, ", ")
}
